version: '3.7'

services:
  zoo1:
    image: zookeeper
    container_name: zoo1
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./jmx_exporter:/jmx_exporter

  zoo2:
    image: zookeeper
    container_name: zoo2
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./jmx_exporter:/jmx_exporter

  zoo3:
    image: zookeeper
    container_name: zoo3
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes:
      - ./jmx_exporter:/jmx_exporter

  kafka:
    #container_name: kafka
    image: wurstmeister/kafka:latest
    ports:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.69.0.50
      KAFKA_HEAP_OPTS: -Xmx6g -Xms6g
      #KAFKA_JMX_OPTS: -javaagent:/jmx_exporter/jmx_prometheus_javaagent-0.12.0.jar=6060:/jmx_exporter/kafka-2_0_0.yml
      KAFKA_JVM_PERFORMANCE_OPTS: -server -XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80
      KAFKA_ZOOKEEPER_CONNECT: 10.69.0.50:2181,10.69.0.50:2182,10.69.0.50:2183
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jmx_exporter:/jmx_exporter
